import streamlit as st
from PIL import Image

image = Image.open('logo.png.png')
st.title(' Cardápio Online ')
st.subheader('PIZZAS PROMOCIONAIS:')
st.markdown('''CALABRESA: MOLHO DE TOMATE, CALABRESA, CEBOLA E ORÉGANO R$32,99
MUSSARELA: MOLHO DE TOMATE, MUSSARELA E ORÉGANO R$32,99
CALABRESA II: MOLHO DE TOMATE, MUSSARELA, CALABRESA,
CEBOLA E ORÉGANO R$35,99
BAIANA: MOLHO DE TOMATE, CALABRESA, OVO, CEBOLA, MOLHO DE PIMENTA, MUSSARELA, E ORÉGANO R$35,99
MARGUERITA: MOLHO DE TOMATE, MUSSARELA, MANJERICÃO E ORÉGANO R$35,99''')
st.subheader(' PIZZAS TRADICIONAIS R$39,99')
st.markdown('''ATUM: MOLHO DE TOMATE, MUSSARELA, ATUM, CEBOLA, AZEITE E ORÉGANO 
ALHO: MOLHO DE TOMATE, MUSSARELA, TOMATE FATIADO, AOLHO FRITO E ORÉGANO 
BACON: MOLHO DE TOMATE, MUSSARELA, TOMATE FATIADO, CEBOLA, BACON E ORÉGANO
BRÓCOLIS: MOLHO DE TOMATE, MUSSARELA, BRÓCOLIS, BACON E ORÉGANO 
DOIS QUEIJOS: MOLHO DE TOMATE, MUSSARELA, CATUPIRY E ORÉGANO
MILHO: MOLHO DE TOMATE, MILHO VERDE, MUSSARELA, TOMATE FATIADO E ORÉGANO
ESCAROLA: MOLHO DE TOMATE, MUSSARELA, ESCAROLA REFOGADA, BACON E ORÉGANO
FRANGO COM CATUPIRY: MOLHO DE TOMATE, CATUPIRY, FRANGO DESFIADO, E ORÉGANO
PALMITO: MOLHO DE TOMATE, MUSSARELA, PALMITO E ORÉGANO
LOMBO CANADENSE: MOLHO DE TOMATE, MUSSARELA, LOMBO CANADENSE, CEBOLA, BACON E ORÉGANO''')

st.subheader(' PIZZAS ESPECIAIS R$42,99')
st.markdown('''A MODA: MOLHO DE TOMATE, MUSSARELA, CATUPIRY, PEPERONI E ORÉGANO
BIG MAC: 8 HMBURGUERES, MUSSARELA, MOLHO
ESPECIAL, CEBOLA, PICLES E GERGELIM 
IMPÉRIO: MOLHO DE TOMATE, CARNE MOIDA, CEBOLA, PIMENTÃO, CATUPIRY E ORÉGANO
PORTUGUESA: MOLHO DE TOMATE, MUSSARELA, PRESUNTO, OVOS, CEBOLA, AZEITONA, ERVILHA E ORÉGANO ''')

st.subheader('PIZZAS DOCES R$39,99')
st.markdown('''
BANANA COM MUSSARELA
M&M'S
PRESTIGIO
ROMEU COM JULIETA''')
